/* GENERATED by scripts/gen-theme.py from theme/templates/quickshell/Theme.qml.in — edit the template, not this file. */
pragma Singleton
import QtQuick
import Quickshell

// Enhalation tokens for Quickshell (docs/capture-ui.md §2.1). Every value comes from the
// oracle as the same CSS string rofi and swaync get; the helpers below only change format
// (Qt wants #AARRGGBB, integers and bezier lists), never colour.
Singleton {
    function css(hex) {                                  // "#rrggbb" / "#rrggbbaa" → color
        const h = hex.slice(1);
        const a = h.length === 8 ? parseInt(h.slice(6, 8), 16) / 255 : 1;
        return Qt.rgba(parseInt(h.slice(0, 2), 16) / 255, parseInt(h.slice(2, 4), 16) / 255,
                       parseInt(h.slice(4, 6), 16) / 255, a);
    }
    function bezier(s) {                                 // "cubic-bezier(a, b, c, d)" → spline
        const n = s.match(/-?[\d.]+/g).map(Number);
        return [n[0], n[1], n[2], n[3], 1, 1];
    }
    function shadow(s) {                                 // CSS box-shadow list → layers
        return s.split(/,\s*(?![^(]*\))/).map(layer => {
            const p = layer.trim().split(/\s+/);
            return { x: parseFloat(p[0]), y: parseFloat(p[1]), blur: parseFloat(p[2]),
                     spread: parseFloat(p[3]), color: css(p[4]) };
        });
    }
    // CSS linear-gradient(<deg>) line for a w×h box: [x1, y1, x2, y2].
    function gradientLine(deg, w, h) {
        const t = deg * Math.PI / 180, dx = Math.sin(t), dy = -Math.cos(t);
        const len = Math.abs(w * dx) + Math.abs(h * dy);
        return [w / 2 - dx * len / 2, h / 2 - dy * len / 2, w / 2 + dx * len / 2, h / 2 + dy * len / 2];
    }

    readonly property string font: "CartographCF Nerd Font"

    // colour
    readonly property color ink: css("#cdd6f4")
    readonly property color inkMuted: css("#a6adc8")
    readonly property color accent: css("#cba6f7")
    readonly property color spark: css("#94e2d5")
    readonly property color danger: css("#f38ba8")
    readonly property color dangerSoft: css("#f38ba81f")
    readonly property color dangerRim: css("#f38ba866")
    readonly property color onHalo: css("#11111b")
    readonly property color pill: css("#cdd6f417")
    readonly property color pillHover: css("#cdd6f421")
    readonly property color pillTop: css("#f5e0dc1d")
    readonly property color well: css("#11111b99")
    readonly property color rim: css("#45475a8c")
    readonly property color glassEdge: css("#f5e0dc29")
    readonly property color tint: css("#f5e0dc07")
    readonly property color tintEnd: css("#f5e0dc00")
    readonly property color glassDesktop: css("#1e1e2ef7")
    readonly property color thumb: css("#9399b2")
    readonly property color thumbHi: css("#b2b7c9")
    readonly property color thumbShadow: css("#11111b59")
    readonly property color captureScrim: css("#11111b8c")

    // depth
    readonly property var glassFloat: shadow("0 30px 60px -20px #08080de6, 0 12px 24px -12px #08080d99")
    readonly property var haloGlow: shadow("0 10px 34px -8px #cba6f780, 0 6px 22px -8px #fab38766")
    readonly property var haloGlowLift: shadow("0 18px 48px -8px #cba6f7a6, 0 8px 28px -8px #fab3878c")
    readonly property real opacityDisabled: 0.42

    // motion
    readonly property int durPress: parseInt("90ms")
    readonly property int durHover: parseInt("180ms")
    readonly property int durExit: parseInt("150ms")
    readonly property int durEnter: parseInt("280ms")
    readonly property int durSlide: parseInt("420ms")
    readonly property var easeOutExpo: bezier("cubic-bezier(0.16, 1, 0.3, 1)")
    readonly property var easeSpring: bezier("cubic-bezier(0.34, 1.56, 0.64, 1)")
    readonly property var easePress: bezier("cubic-bezier(0.3, 0, 0.2, 1)")
    readonly property var easeExit: bezier("cubic-bezier(0.5, 0, 0.75, 0)")

    // shape and space
    readonly property int radiusSm: parseInt("12px")
    readonly property int radiusLg: parseInt("26px")
    readonly property int space2: parseInt("8px")
    readonly property int space3: parseInt("12px")
    readonly property int space4: parseInt("16px")

    // recording island (§4); core-stop.png is baked at stopW × stopH
    readonly property int islandW: 368
    readonly property int islandPad: 16
    readonly property int islandGap: 8
    readonly property int islandSideW: 132
    readonly property int stopW: 196
    readonly property int stopH: 42

    // glyphs
    readonly property string gVolume: ""
    readonly property string gStop: ""
    readonly property string gDelete: ""
    readonly property string gPlay: ""
    readonly property string gCheck: ""
    readonly property string gCopy: ""
    readonly property string gWarn: ""
    readonly property string gFolder: ""
    readonly property string gArea: ""
    readonly property string gScreen: ""
    readonly property string gWindow: ""
    readonly property string gCamera: ""
    readonly property string gRecord: ""
    readonly property string gPhoto: ""
    readonly property string gVideo: ""
    readonly property string gPointer: ""
    readonly property string gClose: ""
}
