#!/usr/bin/env bash
#
# gen-keybindings.sh — regenerate docs/keybindings.md from wayfire.ini.
#
# Hand-written keybinding tables rot the moment you rebind something. This reads
# the config, so the document cannot disagree with it.
#
#   ./scripts/gen-keybindings.sh          write docs/keybindings.md
#   ./scripts/gen-keybindings.sh --check  exit 1 if the file is out of date

set -euo pipefail
REPO="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
INI="$REPO/home/.config/wayfire.ini"
OUT="$REPO/docs/keybindings.md"

[[ -f $INI ]] || { echo "no wayfire.ini at $INI" >&2; exit 1; }

generate() {
python3 - "$INI" <<'PY'
import re, sys, collections

path = sys.argv[1]
section, sections = None, collections.OrderedDict()
for raw in open(path, encoding='utf-8', errors='replace'):
    line = raw.strip()
    if not line or line.startswith('#'):
        continue
    m = re.match(r'^\[([^\]]+)\]$', line)
    if m:
        section = m.group(1)
        sections.setdefault(section, [])
        continue
    if '=' not in line or section is None:
        continue
    key, val = (p.strip() for p in line.split('=', 1))
    sections[section].append((key, val))

KEYNAMES = {
    'ENTER': 'Enter', 'ESC': 'Esc', 'TAB': 'Tab', 'SYSRQ': 'PrtSc',
    'LEFT': '←', 'RIGHT': '→', 'UP': '↑', 'DOWN': '↓',
    'VOLUMEUP': 'Vol +', 'VOLUMEDOWN': 'Vol −', 'MUTE': 'Mute', 'MICMUTE': 'Mic mute',
    'BRIGHTNESSUP': 'Bright +', 'BRIGHTNESSDOWN': 'Bright −',
}
KEYNAMES.update({f'KP{i}': f'Num {i}' for i in range(10)})


def pretty(binding: str) -> str:
    """<super> KEY_W  ->  Super + W"""
    out = []
    for alt in binding.split('|'):
        parts = []
        for tok in alt.split():
            if tok.startswith('<') and tok.endswith('>'):
                parts.append(tok[1:-1].capitalize())
            elif tok.startswith('KEY_'):
                k = tok[4:]
                parts.append(KEYNAMES.get(k, k.title() if len(k) > 1 else k))
            elif tok.startswith('BTN_'):
                parts.append({'LEFT': 'Left-click', 'RIGHT': 'Right-click'}.get(tok[4:], tok))
            else:
                parts.append(tok)
        out.append(' + '.join(parts))
    return ' &nbsp;*or*&nbsp; '.join(out)

def esc(s: str) -> str:
    return s.replace('|', '\\|').replace('*', '\\*')

rows_cmd = []
cmds = dict(sections.get('command', []))
for key, val in sections.get('command', []):
    if not key.startswith(('binding_', 'repeatable_binding_')):
        continue
    name = key.split('binding_', 1)[1]
    action = cmds.get(f'command_{name}')
    if action is None:
        continue
    action = re.sub(r'^sh -c ', '', action)
    action = action.replace('setsid -f ', '').replace('$HOME', '~')
    action = action.replace('"', '').replace("'", '').strip()
    if len(action) > 62:
        action = action[:59] + '…'
    rep = ' *(repeats)*' if key.startswith('repeatable_') else ''
    rows_cmd.append((pretty(val), name.replace('_', ' '), f'`{esc(action)}`{rep}'))

# Plugin bindings: anything whose value looks like a key combination.
KEYISH = re.compile(r'(<\w+>|KEY_|BTN_)')
SKIP_SECTIONS = {'command', 'core', 'input', 'autostart', 'decoration'}
rows_plug = []
for sec, items in sections.items():
    if sec in SKIP_SECTIONS or sec.startswith('output:'):
        continue
    for key, val in items:
        if not KEYISH.search(val):
            continue
        rows_plug.append((pretty(val), sec, key.replace('_', ' ')))

for sec in ('core',):
    for key, val in sections.get(sec, []):
        if KEYISH.search(val):
            rows_plug.append((pretty(val), 'core', key.replace('_', ' ')))

w = sys.stdout.write
w("# Keybindings\n\n")
w("<!-- GENERATED by scripts/gen-keybindings.sh from home/.config/wayfire.ini.\n")
w("     Do not edit by hand — rebind in wayfire.ini and re-run the script. -->\n\n")
w("Regenerate after changing a binding:\n\n```sh\n./scripts/gen-keybindings.sh\n```\n\n")

w("## Commands\n\nLaunching things and running scripts — the `[command]` section.\n\n")
w("| Keys | Action | Runs |\n|---|---|---|\n")
for k, n, a in rows_cmd:
    w(f"| {k} | {n} | {a} |\n")

w("\n## Window and workspace management\n\nBindings owned by individual plugins.\n\n")
w("| Keys | Plugin | Action |\n|---|---|---|\n")
for k, s, n in sorted(rows_plug, key=lambda r: (r[1], r[2])):
    w(f"| {k} | `{s}` | {n} |\n")

total = len(rows_cmd) + len(rows_plug)
w(f"\n---\n\n{total} bindings across {len({r[1] for r in rows_plug}) + 1} sections.\n")
PY
}

if [[ ${1:-} == --check ]]; then
  if diff -q <(generate) "$OUT" >/dev/null 2>&1; then
    echo "docs/keybindings.md is up to date"
  else
    echo "docs/keybindings.md is STALE — run ./scripts/gen-keybindings.sh" >&2
    exit 1
  fi
else
  generate > "$OUT"
  echo "wrote $OUT ($(wc -l < "$OUT") lines)"
fi
