#!/usr/bin/env python3
"""gen-theme.py — render theme/templates/*.in into the live rofi and swaync files.

All colour math, the contrast gate and the grain baking live in
theme/enhalation/enhalation_ref.py. This script only substitutes placeholders,
refuses to write if the gate fails, and writes the baked images. See
docs/enhalation-desktop.md §1.

  ./scripts/gen-theme.py           write every output
  ./scripts/gen-theme.py --check   exit 1 if any output is out of date

Placeholders: {{token-name}} (a resolved Mocha token or a §2 derived token) and
{{glyph.NAME}} (the §6 table). Anything else inside {{ }} is an error.
"""
import argparse
import hashlib
import os
import re
import struct
import sys
import zlib

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, "theme", "enhalation"))
import enhalation_ref as ref  # noqa: E402

TEMPLATES = os.path.join(REPO, "theme", "templates")

# template (under theme/templates) -> output (under the repo). The outputs are
# `link` entries in dots.conf, so writing them changes the running desktop.
OUTPUTS = {
    "rofi/launcher.rasi.in": "home/.config/rofi/config/launcher.rasi",
    "swaync/style.css.in": "home/.config/swaync/style.css",
    "quickshell/Theme.qml.in": "home/.config/quickshell/enhalation/Theme.qml",
}
# Baked images (enhalation_ref.bake) and where each is written.
ASSETS = {
    "home/.config/swaync/assets": ("glass-grain.png", "switch-on.png"),
    "home/.config/quickshell/enhalation/assets": ("glass-grain.png", "shutter-60.png", "core-stop.png"),
}

# The only private-use code points a template may name: enhalation-desktop.md §6, plus the
# recording island's (capture-ui.md §4; folder-open is the preview's "Show in folder").
GLYPHS = {
    "launch": 0xF135,
    "windows": 0xF2D0,
    "clip": 0xF0EA,
    "delete": 0xF1F8,
    "volume": 0xF028,
    "stop": 0xF04D,
    "play": 0xF04B,
    "check": 0xF00C,
    "copy": 0xF0C5,
    "warn": 0xF071,
    "folder-open": 0xF07C,
    # capture overlay (capture-ui.md §3)
    "area": 0xF125,
    "screen": 0xF108,
    "window": 0xF2D2,
    "camera": 0xF030,
    "record": 0xF111,
    "photo": 0xF03E,
    "video": 0xF03D,
    "pointer": 0xF245,
    "close": 0xF00D,
}

PLACEHOLDER = re.compile(r"\{\{([^{}]*)\}\}")
HEADER = ("/* GENERATED by scripts/gen-theme.py from theme/templates/{src} "
          "— edit the template, not this file. */\n")


def render(src, values):
    errors, lines = [], []
    with open(os.path.join(TEMPLATES, src), encoding="utf-8") as f:
        for n, line in enumerate(f, 1):
            def sub(m):
                key = m.group(1)
                if key.startswith("glyph."):
                    if key[6:] in GLYPHS:
                        return chr(GLYPHS[key[6:]])
                elif key in values:
                    return values[key]
                errors.append(f"theme/templates/{src}:{n}: unknown placeholder {{{{{key}}}}}")
                return m.group(0)
            out = PLACEHOLDER.sub(sub, line)
            if "{{" in PLACEHOLDER.sub("", line) or "}}" in PLACEHOLDER.sub("", line):
                errors.append(f"theme/templates/{src}:{n}: malformed placeholder")
            lines.append(out)
    if errors:
        raise SystemExit("gen-theme: " + "\n  ".join(errors))
    return HEADER.format(src=src) + "".join(lines)


def decode_png(data):
    """RGBA bytes of a PNG written by ref.png_bytes (8-bit RGBA, filter 0 only)."""
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        return None
    pos, idat, w = 8, b"", 0
    while pos < len(data):
        length, kind = struct.unpack(">I4s", data[pos:pos + 8])
        body = data[pos + 8:pos + 8 + length]
        if kind == b"IHDR":
            w, _h, depth, colour = struct.unpack(">IIBB", body[:10])
            if (depth, colour) != (8, 6):
                return None
        elif kind == b"IDAT":
            idat += body
        pos += 12 + length
    raw, stride, rgba = zlib.decompress(idat), w * 4 + 1, bytearray()
    for row in range(len(raw) // stride):
        line = raw[row * stride:(row + 1) * stride]
        if line[0] != 0:
            return None
        rgba += line[1:]
    return bytes(rgba)


def build():
    tok = ref.load_tokens()
    der = ref.derive(tok)
    rows, ok = ref.contrast_table(tok, der)
    if not ok:
        bad = [r for r in rows if r[-1] == "FAIL"]
        sys.exit("gen-theme: contrast gate FAILED — nothing written\n" +
                 "\n".join(f"  {b:6} {s:12} {t:12} {r:5.2f} < {need}" for b, s, _, t, r, need, _ in bad))
    values = {k: str(v) for k, v in {**tok, **der}.items()}
    texts = {out: render(src, values) for src, out in OUTPUTS.items()}
    baked = ref.bake(tok, der)
    images = {os.path.join(d, name): baked[name] for d, names in ASSETS.items() for name in names}
    minima = {}
    for _b, surface, _hex, _t, r, _need, verdict in rows:
        if verdict != "forbidden":
            minima[surface] = min(r, minima.get(surface, r))
    return texts, images, minima


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="exit 1 if any output is out of date")
    args = ap.parse_args()
    texts, images, minima = build()

    stale = []
    for out, text in texts.items():
        path = os.path.join(REPO, out)
        current = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if current != text:
            stale.append(out)
            if not args.check:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text)
    for out, (w, h, rgba) in images.items():
        path = os.path.join(REPO, out)
        current = decode_png(open(path, "rb").read()) if os.path.exists(path) else None
        if current != rgba:
            stale.append(out)
            if not args.check:
                os.makedirs(os.path.dirname(path), exist_ok=True)
                with open(path, "wb") as f:
                    f.write(ref.png_bytes(w, h, rgba))

    if args.check:
        if stale:
            print("gen-theme: out of date — run ./scripts/gen-theme.py", file=sys.stderr)
            for out in stale:
                print(f"  {out}", file=sys.stderr)
            return 1
        return 0

    print("gen-theme: contrast gate PASS — minimum ratio per surface:")
    print("  " + "  ".join(f"{s} {r:.2f}" for s, r in sorted(minima.items())))
    for out in list(texts) + list(images):
        print(f"  {'wrote    ' if out in stale else 'unchanged'} {out}")
    for out, (_w, _h, rgba) in images.items():
        print(f"  {os.path.basename(out)} raw-RGBA sha256 {hashlib.sha256(rgba).hexdigest()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
